1
name: Java CI with Maven
2
3
on:
4
  push:
5
    branches: [ main ]
6
  pull_request:
7
    branches: [ main ]
8
9
jobs:
10
11
  compile:
12
    runs-on: ubuntu-latest
13
    name: Running Java ${{ matrix.java }} compile
14
    steps:
15
    - uses: actions/checkout@v2
16
    - name: Set up JDK 1.8
17
      uses: actions/setup-java@v1
18
      with:
19
        java-version: 1.8
20
    - name: Compile code
21
      run: mvn compile
22
23
  test:
24
    runs-on: ubuntu-latest
25
    name: Running tests
26
    needs: compile
27
    steps:
28
      - uses: actions/checkout@v2
29
      - name: Set up JDK 1.8
30
        uses: actions/setup-java@v1
31
        with:
32
          java-version: 1.8
33
      - name: Run unit tests
34
        run: mvn test
35
36
  build:
37
    runs-on: ubuntu-latest
38
    name: Run mvn build and generate coverage report
39
    needs: test
40
    steps:
41
      - uses: actions/checkout@v2
42
      - name: Set up JDK 1.8
43
        uses: actions/setup-java@v1
44
        with:
45
          java-version: 1.8
46
      - name: Build with Maven
47
        run: mvn -B package --file pom.xml -Dmaven.test.skip=true
48
      - name: generate report codecov
49
        run: mvn cobertura:cobertura
50
      - name: Upload coverage
51
        if: success()
52
        run: |
53
          curl -s https://codecov.io/bash | bash
54
        env:
55
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
56
        shell: bash
